import {ASSET_CATEGORIES} from '../asset-categories.js';

export const COMMODITY_TICKERS = [
    {label: 'BAR', symbol: 'bar.us', keywords: ['gold bullion', 'physical gold']},
    {label: 'BCI', symbol: 'bci.us', keywords: ['broad commodities', 'commodity index']},
    {label: 'BNO', symbol: 'bno.us', keywords: ['brent oil', 'oil etf']},
    {label: 'BOIL', symbol: 'boil.us', keywords: ['leveraged natural gas', 'natural gas etf']},
    {label: 'CANE', symbol: 'cane.us', keywords: ['sugar fund', 'sugar etf']},
    {label: 'CMDY', symbol: 'cmdy.us', keywords: ['commodity strategy', 'broad commodities']},
    {label: 'COM', symbol: 'com.us', keywords: ['commodity index', 'broad commodities']},
    {label: 'COMT', symbol: 'comt.us', keywords: ['commodity total return', 'broad commodities']},
    {label: 'COPX', symbol: 'copx.us', keywords: ['copper miners', 'mining']},
    {label: 'CORN', symbol: 'corn.us', keywords: ['corn fund', 'agriculture']},
    {label: 'COWS', symbol: 'cows.us', keywords: ['livestock fund', 'agriculture']},
    {label: 'CPER', symbol: 'cper.us', keywords: ['copper etf', 'copper']},
    {label: 'CUT', symbol: 'cut.us', keywords: ['timber forestry', 'wood']},
    {label: 'Cocoa', symbol: 'cc.f', keywords: ['cocoa futures']},
    {label: 'Coffee', symbol: 'kc.f', keywords: ['coffee futures']},
    {label: 'Copper', symbol: 'hg.f', keywords: ['copper futures']},
    {label: 'Corn Futures', symbol: 'zc.f', keywords: ['corn futures']},
    {label: 'Cotton', symbol: 'ct.f', keywords: ['cotton futures']},
    {label: 'Crude Oil Fund', symbol: 'dbo.us', keywords: ['oil fund', 'crude oil']},
    {label: 'DBA', symbol: 'dba.us', keywords: ['agriculture fund', 'agriculture etf']},
    {label: 'DBB', symbol: 'dbb.us', keywords: ['base metals fund', 'metals etf']},
    {label: 'DBC', symbol: 'dbc.us', keywords: ['commodity index', 'commodities']},
    {label: 'DBE', symbol: 'dbe.us', keywords: ['energy fund', 'energy commodities']},
    {label: 'DBP', symbol: 'dbp.us', keywords: ['precious metals fund', 'precious metals']},
    {label: 'DJP', symbol: 'djp.us', keywords: ['commodity etn', 'broad commodities']},
    {label: 'FTGC', symbol: 'ftgc.us', keywords: ['active commodities', 'commodity strategy']},
    {label: 'GC.F', symbol: 'gc.f', keywords: ['gold futures']},
    {label: 'GDX', symbol: 'gdx.us', keywords: ['gold miners etf', 'gold miners']},
    {label: 'GDXJ', symbol: 'gdxj.us', keywords: ['junior gold miners', 'gold miners']},
    {label: 'GF.F', symbol: 'gf.f', keywords: ['feeder cattle futures', 'livestock']},
    {label: 'GLD', symbol: 'gld.us', keywords: ['gold etf']},
    {label: 'GLTR', symbol: 'gltr.us', keywords: ['precious metals basket', 'multi metal']},
    {label: 'GNR', symbol: 'gnr.us', keywords: ['natural resources', 'resources etf']},
    {label: 'GSG', symbol: 'gsg.us', keywords: ['commodity index', 'broad commodities']},
    {label: 'Gasoline', symbol: 'rb.f', keywords: ['gasoline futures']},
    {label: 'Gold', symbol: 'xauusd', priceDecimals: 0, keywords: ['xau', 'spot gold']},
    {label: 'HE.F', symbol: 'he.f', keywords: ['lean hogs futures', 'livestock']},
    {label: 'Heating Oil', symbol: 'ho.f', keywords: ['heating oil futures']},
    {label: 'IAU', symbol: 'iau.us', keywords: ['gold trust etf', 'gold etf']},
    {label: 'IYM', symbol: 'iym.us', keywords: ['basic materials', 'materials etf']},
    {label: 'Kansas Wheat', symbol: 'ke.f', keywords: ['wheat futures', 'kansas wheat']},
    {label: 'LB.F', symbol: 'lb.f', keywords: ['lumber futures', 'lumber']},
    {label: 'LE.F', symbol: 'le.f', keywords: ['live cattle futures', 'livestock']},
    {label: 'LIT', symbol: 'lit.us', keywords: ['lithium', 'battery materials']},
    {label: 'METL', symbol: 'metl.us', keywords: ['metals and mining', 'mining']},
    {label: 'MEXX', symbol: 'mexx.us', keywords: ['metals and miners', 'mining']},
    {label: 'MOO', symbol: 'moo.us', keywords: ['agribusiness', 'agriculture equities']},
    {label: 'MXI', symbol: 'mxi.us', keywords: ['global materials', 'materials etf']},
    {label: 'NLR', symbol: 'nlr.us', keywords: ['nuclear energy', 'uranium']},
    {label: 'Natural Gas', symbol: 'ng.f', keywords: ['nat gas', 'gas futures']},
    {label: 'Nickel', symbol: 'ni.f', keywords: ['nickel futures']},
    {label: 'OJ.F', symbol: 'oj.f', keywords: ['orange juice futures']},
    {label: 'PALL', symbol: 'pall.us', keywords: ['palladium etf', 'palladium']},
    {label: 'PDBC', symbol: 'pdbc.us', keywords: ['commodity strategy', 'broad commodities']},
    {label: 'PICK', symbol: 'pick.us', keywords: ['metals and mining', 'mining']},
    {label: 'PPLT', symbol: 'pplt.us', keywords: ['platinum etf', 'platinum']},
    {label: 'PYZ', symbol: 'pyz.us', keywords: ['materials momentum', 'materials etf']},
    {label: 'Palladium', symbol: 'pa.f', keywords: ['palladium futures']},
    {label: 'Platinum', symbol: 'pl.f', keywords: ['platinum futures']},
    {label: 'REMX', symbol: 'remx.us', keywords: ['rare earth miners', 'rare earths']},
    {label: 'SB.F', symbol: 'sb.f', keywords: ['sugar futures']},
    {label: 'SGOL', symbol: 'sgol.us', keywords: ['gold trust', 'gold etf']},
    {label: 'SI.F', symbol: 'si.f', keywords: ['silver futures']},
    {label: 'SIL', symbol: 'sil.us', keywords: ['silver miners', 'silver miners']},
    {label: 'SILJ', symbol: 'silj.us', keywords: ['junior silver miners', 'silver miners']},
    {label: 'SLV', symbol: 'slv.us', keywords: ['silver etf']},
    {label: 'SOYB', symbol: 'soyb.us', keywords: ['soybean fund', 'agriculture']},
    {label: 'Silver', symbol: 'xagusd', keywords: ['xag', 'spot silver']},
    {label: 'Soybean Meal', symbol: 'zm.f', keywords: ['soybean meal futures']},
    {label: 'Soybean Oil', symbol: 'zl.f', keywords: ['soybean oil futures']},
    {label: 'Soybeans', symbol: 'zs.f', keywords: ['soybean futures']},
    {label: 'TAN', symbol: 'tan.us', keywords: ['solar materials', 'clean energy']},
    {label: 'UCO', symbol: 'uco.us', keywords: ['leveraged crude oil', 'oil etf']},
    {label: 'UGA', symbol: 'uga.us', keywords: ['gasoline fund', 'gasoline etf']},
    {label: 'UNG', symbol: 'ung.us', keywords: ['natural gas etf', 'gas etf']},
    {label: 'UNL', symbol: 'unl.us', keywords: ['natural gas long', 'natural gas curve']},
    {label: 'URA', symbol: 'ura.us', keywords: ['uranium etf', 'uranium']},
    {label: 'URNM', symbol: 'urnm.us', keywords: ['uranium miners', 'uranium']},
    {label: 'USCI', symbol: 'usci.us', keywords: ['commodity index', 'commodity strategy']},
    {label: 'USL', symbol: 'usl.us', keywords: ['12 month oil', 'oil etf']},
    {label: 'USO', symbol: 'uso.us', keywords: ['oil etf', 'crude oil']},
    {label: 'VDE', symbol: 'vde.us', keywords: ['energy etf', 'energy sector']},
    {label: 'WEAT', symbol: 'weat.us', keywords: ['wheat fund', 'agriculture']},
    {label: 'WOOD', symbol: 'wood.us', keywords: ['timber', 'wood equities']},
    {label: 'Wheat', symbol: 'zw.f', keywords: ['wheat futures']},
    {label: 'XES', symbol: 'xes.us', keywords: ['oil services', 'energy services']},
    {label: 'XLB', symbol: 'xlb.us', keywords: ['materials sector', 'materials etf']},
    {label: 'XME', symbol: 'xme.us', keywords: ['metals mining', 'miners etf']},
    {label: 'XOP', symbol: 'xop.us', keywords: ['oil gas explorers', 'energy exploration']},
    {label: 'Zinc', symbol: 'zn.f', keywords: ['zinc futures']},
].map(entry => ({
    assetCategory: ASSET_CATEGORIES.COMMODITY,
    label: entry.label,
    symbol: entry.symbol,
    priceDecimals: entry.priceDecimals ?? 2,
    keywords: [...entry.keywords],
}));
