import {ASSET_CATEGORIES} from '../asset-categories.js';

export const GERMANY_EQUITY_TICKERS = [
    {label: '1U1', keywords: ['1&1']},
    {label: 'ADN1', keywords: ['adtran networks', 'adtran']},
    {label: 'ADS', keywords: ['adidas']},
    {label: 'AIXA', keywords: ['aixtron']},
    {label: 'ALV', keywords: ['allianz']},
    {label: 'BAS', keywords: ['basf']},
    {label: 'BAYN', keywords: ['bayer']},
    {label: 'BC8', keywords: ['bechtle']},
    {label: 'BEI', keywords: ['beiersdorf']},
    {label: 'BMW', keywords: ['bmw', 'bayerische motoren werke']},
    {label: 'BNR', keywords: ['brenntag']},
    {label: 'BOSS', keywords: ['hugo boss']},
    {label: 'BVB', keywords: ['borussia dortmund']},
    {label: 'CBK', keywords: ['commerzbank']},
    {label: 'CON', keywords: ['continental']},
    {label: 'CWC', keywords: ['cewe']},
    {label: 'DB1', keywords: ['deutsche boerse', 'deutsche borse']},
    {label: 'DBAN', keywords: ['deutsche beteiligungs', 'deutsche beteiligungs ag']},
    {label: 'DBK', keywords: ['deutsche bank']},
    {label: 'DEZ', keywords: ['deutz']},
    {label: 'DHER', keywords: ['delivery hero']},
    {label: 'DHL', keywords: ['dhl', 'deutsche post dhl']},
    {label: 'DRW3', keywords: ['draegerwerk', 'dragerwerk']},
    {label: 'DTE', keywords: ['deutsche telekom']},
    {label: 'DTG', keywords: ['daimler truck']},
    {label: 'DUE', keywords: ['duerr', 'durr']},
    {label: 'EKT', keywords: ['energiekontor']},
    {label: 'ELG', keywords: ['elmos semiconductor']},
    {label: 'EOAN', keywords: ['eon']},
    {label: 'EUZ', keywords: ['eckert ziegler', 'eckert & ziegler']},
    {label: 'EVD', keywords: ['cts eventim']},
    {label: 'EVK', keywords: ['evonik']},
    {label: 'EVT', keywords: ['evotec']},
    {label: 'FME', keywords: ['fresenius medical care']},
    {label: 'FNTN', keywords: ['freenet']},
    {label: 'FPE3', keywords: ['fuchs', 'fuchs se']},
    {label: 'FRA', keywords: ['fraport']},
    {label: 'FRE', keywords: ['fresenius']},
    {label: 'G1A', keywords: ['gea group', 'gea']},
    {label: 'GBF', keywords: ['bilfinger']},
    {label: 'GFT', keywords: ['gft technologies']},
    {label: 'GXI', keywords: ['gerresheimer']},
    {label: 'HAG', keywords: ['hensoldt']},
    {label: 'HDD', keywords: ['heidelberger druckmaschinen']},
    {label: 'HEI', keywords: ['heidelberg materials', 'heidelbergcement']},
    {label: 'HFG', keywords: ['hellofresh', 'hello fresh']},
    {label: 'HLE', keywords: ['hella']},
    {label: 'HNR1', keywords: ['hannover rueck', 'hannover re']},
    {label: 'HOT', keywords: ['hochtief']},
    {label: 'HYQ', keywords: ['hypoport']},
    {label: 'IFX', keywords: ['infineon']},
    {label: 'INDU', keywords: ['indus holding']},
    {label: 'JEN', keywords: ['jenoptik']},
    {label: 'JUN3', keywords: ['jungheinrich']},
    {label: 'KBX', keywords: ['knorr-bremse', 'knorr bremse']},
    {label: 'KCO', keywords: ['kloeckner', 'klockner']},
    {label: 'KGX', keywords: ['kion group', 'kion']},
    {label: 'KRN', keywords: ['krones']},
    {label: 'KSB3', keywords: ['ksb']},
    {label: 'KWS', keywords: ['kws saat']},
    {label: 'LEG', keywords: ['leg immobilien']},
    {label: 'LHA', keywords: ['lufthansa', 'deutsche lufthansa']},
    {label: 'LPK', keywords: ['lpkf laser', 'lpkf laser electronics']},
    {label: 'LXS', keywords: ['lanxess']},
    {label: 'MBB', keywords: ['mbb']},
    {label: 'MBG', keywords: ['mercedes-benz', 'mercedes benz']},
    {label: 'MLP', keywords: ['mlp']},
    {label: 'MRK', keywords: ['merck']},
    {label: 'MTX', keywords: ['mtu aero engines', 'mtu']},
    {label: 'MUV2', keywords: ['munich re', 'muenchener rueck']},
    {label: 'NDA', keywords: ['aurubis']},
    {label: 'NDX1', keywords: ['nordex']},
    {label: 'NEM', keywords: ['nemetschek']},
    {label: 'P911', keywords: ['porsche', 'porsche ag']},
    {label: 'PAH3', keywords: ['porsche automobile holding', 'porsche holding']},
    {label: 'PBB', keywords: ['deutsche pfandbriefbank', 'pbb']},
    {label: 'PSM', keywords: ['prosiebensat1', 'prosieben sat1']},
    {label: 'PUM', keywords: ['puma']},
    {label: 'QIA', keywords: ['qiagen']},
    {label: 'RAA', keywords: ['rational']},
    {label: 'RHM', keywords: ['rheinmetall']},
    {label: 'RWE', keywords: ['rwe']},
    {label: 'S92', keywords: ['sma solar']},
    {label: 'SAP', keywords: ['sap']},
    {label: 'SAX', keywords: ['stroeer', 'stroer']},
    {label: 'SDF', keywords: ['k+s', 'ks']},
    {label: 'SIE', keywords: ['siemens']},
    {label: 'SRT3', keywords: ['sartorius']},
    {label: 'SY1', keywords: ['symrise']},
    {label: 'SZG', keywords: ['salzgitter']},
    {label: 'TEG', keywords: ['tag immobilien']},
    {label: 'TKA', keywords: ['thyssenkrupp']},
    {label: 'TLX', keywords: ['talanx']},
    {label: 'TMV', keywords: ['teamviewer']},
    {label: 'VNA', keywords: ['vonovia']},
    {label: 'VOS', keywords: ['vossloh']},
    {label: 'VOW3', keywords: ['volkswagen', 'volkswagen pref']},
    {label: 'WAF', keywords: ['siltronic']},
    {label: 'WCH', keywords: ['wacker chemie']},
    {label: 'ZAL', keywords: ['zalando']},
].map(entry => ({
    assetCategory: ASSET_CATEGORIES.EQUITY,
    label: entry.label,
    symbol: `${entry.label.toLowerCase()}.de`,
    priceDecimals: entry.priceDecimals ?? 2,
    keywords: [...entry.keywords],
}));
