import {ASSET_CATEGORIES} from '../asset-categories.js';

export const JAPAN_EQUITY_TICKERS = [
    {label: '1301', keywords: ['kyokuyo']},
    {label: '1332', keywords: ['nissui']},
    {label: '1333', keywords: ['umios']},
    {label: '1605', keywords: ['inpex']},
    {label: '1721', keywords: ['comsys holdings']},
    {label: '1801', keywords: ['taisei']},
    {label: '1802', keywords: ['obayashi']},
    {label: '1803', keywords: ['shimizu']},
    {label: '1808', keywords: ['haseko']},
    {label: '1812', keywords: ['kajima']},
    {label: '1925', keywords: ['daiwa house industry']},
    {label: '1928', keywords: ['sekisui house']},
    {label: '1963', keywords: ['jgc holdings']},
    {label: '2002', keywords: ['nisshin seifun group']},
    {label: '2269', keywords: ['meiji holdings']},
    {label: '2282', keywords: ['nh foods']},
    {label: '2413', keywords: ['m3']},
    {label: '2432', keywords: ['dena']},
    {label: '2501', keywords: ['sapporo holdings']},
    {label: '2502', keywords: ['asahi group holdings']},
    {label: '2503', keywords: ['kirin holdings company']},
    {label: '2531', keywords: ['takara holdings']},
    {label: '2768', keywords: ['sojitz']},
    {label: '2801', keywords: ['kikkoman']},
    {label: '2802', keywords: ['ajinomoto']},
    {label: '2871', keywords: ['nichirei']},
    {label: '2914', keywords: ['japan tobacco']},
    {label: '3086', keywords: ['j front retailing']},
    {label: '3092', keywords: ['zozo']},
    {label: '3099', keywords: ['isetan mitsukoshi holdings']},
    {label: '3289', keywords: ['tokyu fudosan holdings']},
    {label: '3382', keywords: ['seven i holdings']},
    {label: '3401', keywords: ['teijin']},
    {label: '3402', keywords: ['toray industries']},
    {label: '3405', keywords: ['kuraray']},
    {label: '3407', keywords: ['asahi kasei']},
    {label: '3436', keywords: ['sumco']},
    {label: '3659', keywords: ['nexon']},
    {label: '3861', keywords: ['oji holdings']},
    {label: '3863', keywords: ['nippon paper industries']},
    {label: '4004', keywords: ['resonac holdings']},
    {label: '4005', keywords: ['sumitomo chemical company']},
    {label: '4021', keywords: ['nissan chemical']},
    {label: '4042', keywords: ['tosoh']},
    {label: '4043', keywords: ['tokuyama']},
    {label: '4061', keywords: ['denka company']},
    {label: '4063', keywords: ['shin etsu chemical']},
    {label: '4151', keywords: ['kyowa kirin']},
    {label: '4183', keywords: ['mitsui chemicals']},
    {label: '4188', keywords: ['mitsubishi chemical group']},
    {label: '4208', keywords: ['ube']},
    {label: '4452', keywords: ['kao']},
    {label: '4502', keywords: ['takeda pharmaceutical company']},
    {label: '4503', keywords: ['astellas pharma']},
    {label: '4506', keywords: ['sumitomo pharma']},
    {label: '4507', keywords: ['shionogi']},
    {label: '4519', keywords: ['chugai pharmaceutical']},
    {label: '4523', keywords: ['eisai']},
    {label: '4568', keywords: ['daiichi sankyo company']},
    {label: '4578', keywords: ['otsuka holdings']},
    {label: '4661', keywords: ['oriental land']},
    {label: '4689', keywords: ['ly']},
    {label: '4704', keywords: ['trend micro']},
    {label: '4751', keywords: ['cyberagent']},
    {label: '4755', keywords: ['rakuten group']},
    {label: '4901', keywords: ['fujifilm holdings']},
    {label: '4902', keywords: ['konica minolta']},
    {label: '4911', keywords: ['shiseido company']},
    {label: '5019', keywords: ['idemitsu kosan']},
    {label: '5020', keywords: ['eneos holdings']},
    {label: '5101', keywords: ['the yokohama rubber company']},
    {label: '5108', keywords: ['bridgestone']},
    {label: '5201', keywords: ['agc']},
    {label: '5202', keywords: ['nippon sheet glass company']},
    {label: '5214', keywords: ['nippon electric glass']},
    {label: '5232', keywords: ['sumitomo osaka cement']},
    {label: '5233', keywords: ['taiheiyo cement']},
    {label: '5301', keywords: ['tokai carbon']},
    {label: '5332', keywords: ['toto']},
    {label: '5333', keywords: ['ngk']},
    {label: '5401', keywords: ['nippon steel']},
    {label: '5406', keywords: ['kobe steel']},
    {label: '5411', keywords: ['jfe holdings']},
    {label: '5541', keywords: ['pacific metals']},
    {label: '5631', keywords: ['the japan steel works']},
    {label: '5706', keywords: ['mitsui kinzoku company']},
    {label: '5711', keywords: ['mitsubishi materials']},
    {label: '5713', keywords: ['sumitomo metal mining']},
    {label: '5714', keywords: ['dowa holdings']},
    {label: '5801', keywords: ['furukawa electric']},
    {label: '5802', keywords: ['sumitomo electric industries']},
    {label: '5803', keywords: ['fujikura']},
    {label: '6098', keywords: ['recruit holdings']},
    {label: '6103', keywords: ['okuma']},
    {label: '6113', keywords: ['amada']},
    {label: '6146', keywords: ['disco']},
    {label: '6178', keywords: ['japan post holdings']},
    {label: '6301', keywords: ['komatsu']},
    {label: '6302', keywords: ['sumitomo heavy industries']},
    {label: '6305', keywords: ['hitachi construction machinery']},
    {label: '6326', keywords: ['kubota']},
    {label: '6361', keywords: ['ebara']},
    {label: '6367', keywords: ['daikin industries']},
    {label: '6471', keywords: ['nsk']},
    {label: '6472', keywords: ['ntn']},
    {label: '6473', keywords: ['jtekt']},
    {label: '6479', keywords: ['minebea mitsumi']},
    {label: '6501', keywords: ['hitachi']},
    {label: '6503', keywords: ['mitsubishi electric']},
    {label: '6504', keywords: ['fuji electric']},
    {label: '6506', keywords: ['yaskawa electric']},
    {label: '6526', keywords: ['socionext']},
    {label: '6594', keywords: ['nidec']},
    {label: '6645', keywords: ['omron']},
    {label: '6674', keywords: ['gs yuasa']},
    {label: '6701', keywords: ['nec']},
    {label: '6702', keywords: ['fujitsu']},
].map(entry => ({
    assetCategory: ASSET_CATEGORIES.EQUITY,
    label: entry.label,
    symbol: `${entry.label.toLowerCase()}.jp`,
    priceDecimals: 2,
    keywords: [...entry.keywords, 'japan', 'tokyo stock exchange', entry.label],
}));
