import {ASSET_CATEGORIES} from '../asset-categories.js';

export const NETHERLANDS_EQUITY_TICKERS = [
    {label: 'AALB', keywords: ['aalberts', 'aalberts nv']},
    {label: 'ABN', keywords: ['abn amro', 'abn amro bank']},
    {label: 'ACOMO', keywords: ['acomo']},
    {label: 'AD', keywords: ['ahold delhaize', 'koninklijke ahold delhaize']},
    {label: 'ADYEN', keywords: ['adyen']},
    {label: 'AGIL', keywords: ['agility capital holding']},
    {label: 'AGN', keywords: ['aegon']},
    {label: 'AJAX', keywords: ['ajax', 'afc ajax']},
    {label: 'AKZA', keywords: ['akzo nobel', 'akzonobel']},
    {label: 'ALFEN', keywords: ['alfen']},
    {label: 'ALLFG', keywords: ['allfunds', 'allfunds group']},
    {label: 'ALX', keywords: ['alumexx']},
    {label: 'AMG', keywords: ['amg critical materials']},
    {label: 'AMUND', keywords: ['almunda professionals']},
    {label: 'APAM', keywords: ['aperam']},
    {label: 'ARCAD', keywords: ['arcadis']},
    {label: 'ASM', keywords: ['asm international']},
    {label: 'ASML', keywords: ['asml']},
    {label: 'ASRNL', keywords: ['asr nederland']},
    {label: 'AVTX', keywords: ['avantium']},
    {label: 'AXS', keywords: ['accsys technologies']},
    {label: 'AZRN', keywords: ['azerion']},
    {label: 'BACE', keywords: ['bm3eac']},
    {label: 'BAMNB', keywords: ['bam', 'koninklijke bam groep']},
    {label: 'BESI', keywords: ['be semiconductor industries', 'besi']},
    {label: 'BEVER', keywords: ['bever holding']},
    {label: 'BFIT', keywords: ['basic-fit']},
    {label: 'BNJ', keywords: ['banijay group']},
    {label: 'BRNL', keywords: ['brunel', 'brunel international']},
    {label: 'CABKA', keywords: ['cabka']},
    {label: 'CABLE', keywords: ['global interconnection group']},
    {label: 'CCEP', keywords: ['coca-cola europacific partners']},
    {label: 'CMCOM', keywords: ['cm.com', 'cmcom']},
    {label: 'CRBN', keywords: ['corbion']},
    {label: 'CSG', keywords: ['csg', 'csg nv']},
    {label: 'CTAC', keywords: ['ctac']},
    {label: 'CTPNV', keywords: ['ctp', 'ctp nv']},
    {label: 'CVC', keywords: ['cvc', 'cvc capital partners']},
    {label: 'DSFIR', keywords: ['dsm-firmenich', 'dsm firmenich']},
    {label: 'EARTH', keywords: ['green earth group']},
    {label: 'EAS2P', keywords: ['ease2pay']},
    {label: 'EBUS', keywords: ['ebusco']},
    {label: 'ECMPA', keywords: ['eurocommercial properties']},
    {label: 'ECT', keywords: ['eurocastle investment']},
    {label: 'ENVI', keywords: ['envipco']},
    {label: 'ERC', keywords: ['er capital']},
    {label: 'EXO', keywords: ['exor']},
    {label: 'FAST', keywords: ['fastned']},
    {label: 'FER', keywords: ['ferrovial']},
    {label: 'FERGR', keywords: ['ferrari group']},
    {label: 'FFARM', keywords: ['forfarmers']},
    {label: 'FLOW', keywords: ['flow traders']},
    {label: 'FUR', keywords: ['fugro']},
    {label: 'HAL', keywords: ['hal trust']},
    {label: 'HAVAS', keywords: ['havas']},
    {label: 'HEIA', keywords: ['heineken']},
    {label: 'HEIJM', keywords: ['heijmans', 'koninklijke heijmans']},
    {label: 'HEIO', keywords: ['heineken holding']},
    {label: 'HOLCO', keywords: ['holland colours']},
    {label: 'HWK', keywords: ['hawick data']},
    {label: 'HYDRA', keywords: ['hydratec industries']},
    {label: 'IMCD', keywords: ['imcd']},
    {label: 'INGA', keywords: ['ing']},
    {label: 'KENDR', keywords: ['kendrion']},
    {label: 'KPN', keywords: ['kpn', 'koninklijke kpn']},
    {label: 'LIGHT', keywords: ['signify']},
    {label: 'LVIDE', keywords: ['lavide holding']},
    {label: 'MICC', keywords: ['magnum ice cream company']},
    {label: 'MORE', keywords: ['morefield group']},
    {label: 'MT', keywords: ['arcelormittal', 'arcelor mittal']},
    {label: 'MTRK', keywords: ['motork']},
    {label: 'NAI', keywords: ['new amsterdam invest']},
    {label: 'NEDAP', keywords: ['nedap']},
    {label: 'NEDSE', keywords: ['nedsense']},
    {label: 'NN', keywords: ['nn group']},
    {label: 'NRP', keywords: ['nepi rockcastle']},
    {label: 'NSE', keywords: ['new sources energy']},
    {label: 'NSI', keywords: ['nsi']},
    {label: 'NXFIL', keywords: ['nx filtration']},
    {label: 'OCI', keywords: ['oci']},
    {label: 'PBH', keywords: ['pb holding']},
    {label: 'PHARM', keywords: ['pharming', 'pharming group']},
    {label: 'PHIA', keywords: ['philips', 'koninklijke philips']},
    {label: 'PNL', keywords: ['postnl']},
    {label: 'PORF', keywords: ['royal delft', 'porceleyne fles']},
    {label: 'PRX', keywords: ['prosus']},
    {label: 'QEV', keywords: ['spear investments']},
    {label: 'RAND', keywords: ['randstad']},
    {label: 'REINA', keywords: ['reinet investments']},
    {label: 'REN', keywords: ['relx']},
    {label: 'SBMO', keywords: ['sbm offshore']},
    {label: 'SHELL', keywords: ['shell']},
    {label: 'SLIGR', keywords: ['sligro food group']},
    {label: 'THEON', keywords: ['theon international']},
    {label: 'TOM2', keywords: ['tomtom']},
    {label: 'TRIO', keywords: ['triodos bank']},
    {label: 'TWEKA', keywords: ['tkh group']},
    {label: 'UMG', keywords: ['universal music group']},
    {label: 'VALUE', keywords: ['value8']},
    {label: 'VLK', keywords: ['van lanschot kempen']},
    {label: 'VPK', keywords: ['vopak', 'koninklijke vopak']},
    {label: 'VVY', keywords: ['vivoryon therapeutics']},
    {label: 'WHA', keywords: ['wereldhave']},
    {label: 'WKL', keywords: ['wolters kluwer']},
].map(entry => ({
    assetCategory: ASSET_CATEGORIES.EQUITY,
    label: entry.label,
    symbol: `${entry.label.toLowerCase()}.nl`,
    priceDecimals: entry.priceDecimals ?? 2,
    keywords: [...entry.keywords],
}));
