import {ASSET_CATEGORIES} from '../asset-categories.js';

export const UK_EQUITY_TICKERS = [
    {label: 'AAF', keywords: ['airtel africa']},
    {label: 'AAL', keywords: ['anglo american']},
    {label: 'ABF', keywords: ['associated british foods']},
    {label: 'ADM', keywords: ['admiral group']},
    {label: 'ANTO', keywords: ['antofagasta']},
    {label: 'AUTO', keywords: ['auto trader']},
    {label: 'AV', keywords: ['aviva']},
    {label: 'AZN', keywords: ['astrazeneca']},
    {label: 'BA', keywords: ['bae systems']},
    {label: 'BAB', keywords: ['babcock international']},
    {label: 'BARC', keywords: ['barclays']},
    {label: 'BATS', keywords: ['british american tobacco']},
    {label: 'BBOX', keywords: ['tritax big box']},
    {label: 'BEZ', keywords: ['beazley']},
    {label: 'BKG', keywords: ['berkeley group']},
    {label: 'BLND', keywords: ['british land']},
    {label: 'BNZL', keywords: ['bunzl']},
    {label: 'BP', keywords: ['bp']},
    {label: 'BRBY', keywords: ['burberry']},
    {label: 'BTRW', keywords: ['barratt redrow', 'barratt developments']},
    {label: 'CCH', keywords: ['coca-cola hbc']},
    {label: 'CNA', keywords: ['centrica']},
    {label: 'CPG', keywords: ['compass group']},
    {label: 'CRDA', keywords: ['croda international']},
    {label: 'CTEC', keywords: ['convatec']},
    {label: 'DCC', keywords: ['dcc']},
    {label: 'DGE', keywords: ['diageo']},
    {label: 'DLN', keywords: ['derwent london']},
    {label: 'DPLM', keywords: ['diploma']},
    {label: 'EDV', keywords: ['endeavour mining']},
    {label: 'ENT', keywords: ['entain']},
    {label: 'EXPN', keywords: ['experian']},
    {label: 'EZJ', keywords: ['easyjet']},
    {label: 'FRAS', keywords: ['frasers group']},
    {label: 'FRES', keywords: ['fresnillo']},
    {label: 'GAW', keywords: ['games workshop']},
    {label: 'GFRD', keywords: ['galliford try']},
    {label: 'GLEN', keywords: ['glencore']},
    {label: 'GSK', keywords: ['gsk', 'glaxosmithkline']},
    {label: 'HIK', keywords: ['hikma pharmaceuticals']},
    {label: 'HLMA', keywords: ['halma']},
    {label: 'HLN', keywords: ['haleon']},
    {label: 'HSBA', keywords: ['hsbc']},
    {label: 'HWDN', keywords: ['howden joinery']},
    {label: 'IAG', keywords: ['international consolidated airlines', 'british airways', 'iberia']},
    {label: 'ICG', keywords: ['icg', 'intermediate capital group']},
    {label: 'IHG', keywords: ['intercontinental hotels']},
    {label: 'III', keywords: ['3i group']},
    {label: 'IMB', keywords: ['imperial brands']},
    {label: 'IMI', keywords: ['imi']},
    {label: 'INF', keywords: ['informa']},
    {label: 'INVP', keywords: ['investec']},
    {label: 'ITRK', keywords: ['intertek']},
    {label: 'JD', keywords: ['jd sports']},
    {label: 'JDW', keywords: ['wetherspoon', 'jd wetherspoon']},
    {label: 'KGF', keywords: ['kingfisher']},
    {label: 'LAND', keywords: ['land securities']},
    {label: 'LGEN', keywords: ['legal & general', 'legal and general']},
    {label: 'LLOY', keywords: ['lloyds banking group']},
    {label: 'LMP', keywords: ['londonmetric property']},
    {label: 'LSEG', keywords: ['london stock exchange group']},
    {label: 'MKS', keywords: ['marks and spencer']},
    {label: 'MNDI', keywords: ['mondi']},
    {label: 'MNG', keywords: ['m&g', 'm and g']},
    {label: 'NG', keywords: ['national grid']},
    {label: 'NWG', keywords: ['natwest group']},
    {label: 'NXT', keywords: ['next']},
    {label: 'OCDO', keywords: ['ocado']},
    {label: 'PCT', keywords: ['polar capital technology trust']},
    {label: 'PRU', keywords: ['prudential']},
    {label: 'PSN', keywords: ['persimmon']},
    {label: 'REL', keywords: ['relx']},
    {label: 'RIO', keywords: ['rio tinto']},
    {label: 'RKT', keywords: ['reckitt', 'reckitt benckiser']},
    {label: 'RMV', keywords: ['rightmove']},
    {label: 'RR', keywords: ['rolls-royce']},
    {label: 'RTO', keywords: ['rentokil initial']},
    {label: 'SBRY', keywords: ['sainsbury', 'j sainsbury']},
    {label: 'SCT', keywords: ['softcat']},
    {label: 'SDLF', keywords: ['standard life', 'phoenix group']},
    {label: 'SDR', keywords: ['schroders']},
    {label: 'SGE', keywords: ['sage group']},
    {label: 'SGRO', keywords: ['segro']},
    {label: 'SHEL', keywords: ['shell']},
    {label: 'SMIN', keywords: ['smiths group']},
    {label: 'SN', keywords: ['smith & nephew', 'smith and nephew']},
    {label: 'SPX', keywords: ['spirax group', 'spirax-sarco']},
    {label: 'SSE', keywords: ['sse']},
    {label: 'STJ', keywords: ['st jamess place', "st james's place"]},
    {label: 'SVT', keywords: ['severn trent']},
    {label: 'TATE', keywords: ['tate & lyle', 'tate and lyle']},
    {label: 'TSCO', keywords: ['tesco']},
    {label: 'TW', keywords: ['taylor wimpey']},
    {label: 'ULVR', keywords: ['unilever']},
    {label: 'UU', keywords: ['united utilities']},
    {label: 'VOD', keywords: ['vodafone']},
    {label: 'WEIR', keywords: ['weir group']},
    {label: 'WIZZ', keywords: ['wizz air']},
    {label: 'WPP', keywords: ['wpp']},
    {label: 'WTB', keywords: ['whitbread']},
].map(entry => ({
    assetCategory: ASSET_CATEGORIES.EQUITY,
    label: entry.label,
    symbol: `${entry.label.toLowerCase()}.uk`,
    priceDecimals: entry.priceDecimals ?? 2,
    keywords: [...entry.keywords],
}));
