import {ASSET_CATEGORIES} from '../asset-categories.js';

export const US_ETF_TICKERS = [
    {label: 'ACWI', keywords: ['acwi', 'etf']},
    {label: 'AGG', keywords: ['agg', 'etf']},
    {label: 'ARKK', keywords: ['ark innovation etf', 'ark']},
    {label: 'AVDV', keywords: ['avdv', 'etf']},
    {label: 'AVUV', keywords: ['avuv', 'etf']},
    {label: 'BIL', keywords: ['treasury bill etf', 'cash etf']},
    {label: 'BITO', keywords: ['bito', 'etf']},
    {label: 'BND', keywords: ['bnd', 'etf']},
    {label: 'BNDW', keywords: ['bndw', 'etf']},
    {label: 'BNDX', keywords: ['bndx', 'etf']},
    {label: 'BOIL', keywords: ['boil', 'etf']},
    {label: 'CIBR', keywords: ['cibr', 'etf']},
    {label: 'CNYA', keywords: ['cnya', 'etf']},
    {label: 'COWZ', keywords: ['cowz', 'etf']},
    {label: 'CQQQ', keywords: ['cqqq', 'etf']},
    {label: 'CWB', keywords: ['cwb', 'etf']},
    {label: 'DGRO', keywords: ['dgro', 'etf']},
    {label: 'DIA', keywords: ['dow etf', 'dow jones']},
    {label: 'DIVO', keywords: ['divo', 'etf']},
    {label: 'EEM', keywords: ['emerging markets etf', 'emerging markets']},
    {label: 'EFA', keywords: ['developed markets etf', 'eafe']},
    {label: 'EMB', keywords: ['emb', 'etf']},
    {label: 'EWT', keywords: ['ewt', 'etf']},
    {label: 'EWW', keywords: ['eww', 'etf']},
    {label: 'EWZ', keywords: ['ewz', 'etf']},
    {label: 'FDN', keywords: ['fdn', 'etf']},
    {label: 'FLOT', keywords: ['flot', 'etf']},
    {label: 'FREL', keywords: ['frel', 'etf']},
    {label: 'FTEC', keywords: ['ftec', 'etf']},
    {label: 'FXA', keywords: ['fxa', 'etf']},
    {label: 'FXI', keywords: ['fxi', 'etf']},
    {label: 'FXY', keywords: ['fxy', 'etf']},
    {label: 'GDX', keywords: ['gold miners etf', 'gold miners']},
    {label: 'GDXJ', keywords: ['gdxj', 'etf']},
    {label: 'GLD', keywords: ['gold etf']},
    {label: 'GLDM', keywords: ['gldm', 'etf']},
    {label: 'GNR', keywords: ['gnr', 'etf']},
    {label: 'GOVT', keywords: ['govt', 'etf']},
    {label: 'HNDL', keywords: ['hndl', 'etf']},
    {label: 'HYG', keywords: ['high yield bond etf', 'junk bonds']},
    {label: 'IAU', keywords: ['gold trust etf', 'gold etf']},
    {label: 'IBIT', keywords: ['ibit', 'etf']},
    {label: 'IEF', keywords: ['7-10 year treasury etf', 'treasury bonds']},
    {label: 'IEFA', keywords: ['core msci eafe etf', 'developed markets']},
    {label: 'IEMG', keywords: ['core emerging markets etf', 'emerging markets']},
    {label: 'IGE', keywords: ['ige', 'etf']},
    {label: 'IGIB', keywords: ['igib', 'etf']},
    {label: 'IGV', keywords: ['igv', 'etf']},
    {label: 'IHI', keywords: ['ihi', 'etf']},
    {label: 'IJH', keywords: ['mid cap etf', 'midcap']},
    {label: 'IJR', keywords: ['small cap etf', 'small cap']},
    {label: 'ITA', keywords: ['ita', 'etf']},
    {label: 'ITB', keywords: ['homebuilders etf', 'home builders']},
    {label: 'ITOT', keywords: ['itot', 'etf']},
    {label: 'IUSB', keywords: ['iusb', 'etf']},
    {label: 'IVES', keywords: ['ives', 'etf']},
    {label: 'IVV', keywords: ['ishares core s&p 500', 's&p 500 etf']},
    {label: 'IVW', keywords: ['ivw', 'etf']},
    {label: 'IWB', keywords: ['iwb', 'etf']},
    {label: 'IWD', keywords: ['iwd', 'etf']},
    {label: 'IWF', keywords: ['iwf', 'etf']},
    {label: 'IWM', keywords: ['russell 2000', 'small cap']},
    {label: 'IWY', keywords: ['iwy', 'etf']},
    {label: 'IYF', keywords: ['iyf', 'etf']},
    {label: 'IYG', keywords: ['iyg', 'etf']},
    {label: 'IYH', keywords: ['iyh', 'etf']},
    {label: 'IYJ', keywords: ['iyj', 'etf']},
    {label: 'IYR', keywords: ['iyr', 'etf']},
    {label: 'IYT', keywords: ['iyt', 'etf']},
    {label: 'IYY', keywords: ['iyy', 'etf']},
    {label: 'JEPI', keywords: ['income etf', 'covered call']},
    {label: 'JEPQ', keywords: ['nasdaq income etf', 'covered call']},
    {label: 'JNK', keywords: ['jnk', 'etf']},
    {label: 'JPST', keywords: ['jpst', 'etf']},
    {label: 'KBE', keywords: ['kbe', 'etf']},
    {label: 'KOLD', keywords: ['kold', 'etf']},
    {label: 'KRE', keywords: ['regional banks etf', 'regional banks']},
    {label: 'LQD', keywords: ['investment grade bonds etf', 'corporate bonds']},
    {label: 'MBB', keywords: ['mbb', 'etf']},
    {label: 'MCHI', keywords: ['mchi', 'etf']},
    {label: 'MDY', keywords: ['mdy', 'etf']},
    {label: 'MGK', keywords: ['mgk', 'etf']},
    {label: 'MINT', keywords: ['mint', 'etf']},
    {label: 'MTUM', keywords: ['mtum', 'etf']},
    {label: 'NOBL', keywords: ['nobl', 'etf']},
    {label: 'ONEQ', keywords: ['oneq', 'etf']},
    {label: 'PBD', keywords: ['pbd', 'etf']},
    {label: 'PDBC', keywords: ['pdbc', 'etf']},
    {label: 'PFF', keywords: ['pff', 'etf']},
    {label: 'QLD', keywords: ['qld', 'etf']},
    {label: 'QQQ', keywords: ['nasdaq 100 etf', 'invesco qqq']},
    {label: 'QQQM', keywords: ['qqqm', 'etf']},
    {label: 'QUAL', keywords: ['qual', 'etf']},
    {label: 'REM', keywords: ['rem', 'etf']},
    {label: 'RPV', keywords: ['rpv', 'etf']},
    {label: 'RSP', keywords: ['rsp', 'etf']},
    {label: 'SCHB', keywords: ['schb', 'etf']},
    {label: 'SCHD', keywords: ['dividend etf', 'schwab dividend']},
    {label: 'SCHF', keywords: ['schf', 'etf']},
    {label: 'SCHG', keywords: ['growth etf', 'schwab growth']},
    {label: 'SCHK', keywords: ['schk', 'etf']},
    {label: 'SCHP', keywords: ['schp', 'etf']},
    {label: 'SCHX', keywords: ['schx', 'etf']},
    {label: 'SGOL', keywords: ['sgol', 'etf']},
    {label: 'SGOV', keywords: ['sgov', 'etf']},
    {label: 'SHV', keywords: ['shv', 'etf']},
    {label: 'SHY', keywords: ['shy', 'etf']},
    {label: 'SLV', keywords: ['silver etf']},
    {label: 'SMH', keywords: ['semiconductor etf', 'chips']},
    {label: 'SOXX', keywords: ['semiconductor etf', 'ishares semiconductor']},
    {label: 'SPDW', keywords: ['spdw', 'etf']},
    {label: 'SPLV', keywords: ['splv', 'etf']},
    {label: 'SPTL', keywords: ['sptl', 'etf']},
    {label: 'SPTS', keywords: ['spts', 'etf']},
    {label: 'SPY', keywords: ['s&p 500 etf', 'spdr']},
    {label: 'SPYG', keywords: ['spyg', 'etf']},
    {label: 'SPYV', keywords: ['spyv', 'etf']},
    {label: 'SSO', keywords: ['sso', 'etf']},
    {label: 'TAN', keywords: ['tan', 'etf']},
    {label: 'TIP', keywords: ['tip', 'etf']},
    {label: 'TLT', keywords: ['treasury', 'bonds']},
    {label: 'TNA', keywords: ['tna', 'etf']},
    {label: 'TQQQ', keywords: ['tqqq', 'etf']},
    {label: 'UCO', keywords: ['uco', 'etf']},
    {label: 'UDOW', keywords: ['udow', 'etf']},
    {label: 'USMV', keywords: ['usmv', 'etf']},
    {label: 'USO', keywords: ['oil etf', 'crude oil']},
    {label: 'VAW', keywords: ['vaw', 'etf']},
    {label: 'VB', keywords: ['vb', 'etf']},
    {label: 'VBK', keywords: ['vbk', 'etf']},
    {label: 'VBR', keywords: ['vbr', 'etf']},
    {label: 'VCLT', keywords: ['vclt', 'etf']},
    {label: 'VCR', keywords: ['vcr', 'etf']},
    {label: 'VCSH', keywords: ['vcsh', 'etf']},
    {label: 'VDC', keywords: ['vdc', 'etf']},
    {label: 'VDE', keywords: ['vde', 'etf']},
    {label: 'VEA', keywords: ['developed markets etf', 'vanguard developed markets']},
    {label: 'VEU', keywords: ['veu', 'etf']},
    {label: 'VFH', keywords: ['vfh', 'etf']},
    {label: 'VGK', keywords: ['vgk', 'etf']},
    {label: 'VGT', keywords: ['information technology etf', 'tech etf']},
    {label: 'VHT', keywords: ['vht', 'etf']},
    {label: 'VIG', keywords: ['vig', 'etf']},
    {label: 'VIS', keywords: ['vis', 'etf']},
    {label: 'VMBS', keywords: ['vmbs', 'etf']},
    {label: 'VNQ', keywords: ['vnq', 'etf']},
    {label: 'VNQI', keywords: ['vnqi', 'etf']},
    {label: 'VOE', keywords: ['voe', 'etf']},
    {label: 'VONG', keywords: ['vong', 'etf']},
    {label: 'VOO', keywords: ['vanguard s&p 500', 's&p 500 etf']},
    {label: 'VPU', keywords: ['vpu', 'etf']},
    {label: 'VTI', keywords: ['total stock market']},
    {label: 'VTV', keywords: ['value etf', 'vanguard value']},
    {label: 'VUG', keywords: ['growth etf', 'vanguard growth']},
    {label: 'VXF', keywords: ['vxf', 'etf']},
    {label: 'VXUS', keywords: ['international stock etf', 'international equities']},
    {label: 'XBI', keywords: ['biotech etf', 'biotechnology']},
    {label: 'XES', keywords: ['xes', 'etf']},
    {label: 'XLE', keywords: ['energy']},
    {label: 'XLF', keywords: ['financials']},
    {label: 'XLK', keywords: ['technology etf', 'tech sector']},
    {label: 'XLP', keywords: ['consumer staples etf', 'staples']},
    {label: 'XLU', keywords: ['utilities etf', 'utilities']},
    {label: 'XLV', keywords: ['health care etf', 'healthcare']},
    {label: 'XLY', keywords: ['consumer discretionary etf', 'discretionary']},
    {label: 'XOP', keywords: ['oil gas explorers etf', 'exploration and production']},
].map(entry => ({
    assetCategory: ASSET_CATEGORIES.ETF,
    label: entry.label,
    symbol: `${entry.label.toLowerCase()}.us`,
    priceDecimals: 2,
    keywords: [...entry.keywords],
}));
