import {ASSET_CATEGORIES} from '../asset-categories.js';

export const US_EQUITY_TICKERS = [
    {label: 'AAPL', keywords: ['apple']},
    {label: 'ABBV', keywords: ['abbvie']},
    {label: 'ABNB', keywords: ['airbnb']},
    {label: 'ADBE', keywords: ['adobe']},
    {label: 'ADI', keywords: ['analog devices']},
    {label: 'ADP', keywords: ['automatic data processing']},
    {label: 'AMAT', keywords: ['applied materials']},
    {label: 'AMD', keywords: ['advanced micro devices']},
    {label: 'AMGN', keywords: ['amgen']},
    {label: 'AMT', keywords: ['american tower']},
    {label: 'AMZN', keywords: ['amazon']},
    {label: 'ANET', keywords: ['arista networks']},
    {label: 'AON', keywords: ['aon']},
    {label: 'APD', keywords: ['air products']},
    {label: 'APH', keywords: ['amphenol']},
    {label: 'APP', keywords: ['applovin']},
    {label: 'ARM', keywords: ['arm holdings']},
    {label: 'AVGO', keywords: ['broadcom']},
    {label: 'AXP', keywords: ['american express']},
    {label: 'BA', keywords: ['boeing']},
    {label: 'BAC', keywords: ['bank of america']},
    {label: 'BK', keywords: ['bank of new york mellon', 'bny mellon']},
    {label: 'BKNG', keywords: ['booking holdings']},
    {label: 'BLK', keywords: ['blackrock']},
    {label: 'BMY', keywords: ['bristol myers squibb']},
    {label: 'BRK.B', symbol: 'brk-b.us', keywords: ['berkshire hathaway', 'berkshire']},
    {label: 'BX', keywords: ['blackstone']},
    {label: 'C', keywords: ['citigroup']},
    {label: 'CAT', keywords: ['caterpillar']},
    {label: 'CB', keywords: ['chubb']},
    {label: 'CDNS', keywords: ['cadence design systems']},
    {label: 'CEG', keywords: ['constellation energy']},
    {label: 'CHTR', keywords: ['charter communications']},
    {label: 'CI', keywords: ['cigna']},
    {label: 'CMCSA', keywords: ['comcast', 'nbcuniversal']},
    {label: 'CMI', keywords: ['cummins']},
    {label: 'COF', keywords: ['capital one']},
    {label: 'COIN', keywords: ['coinbase', 'crypto exchange']},
    {label: 'COP', keywords: ['conocophillips', 'conoco phillips']},
    {label: 'COST', keywords: ['costco']},
    {label: 'CRM', keywords: ['salesforce']},
    {label: 'CSCO', keywords: ['cisco']},
    {label: 'CTAS', keywords: ['cintas']},
    {label: 'CVS', keywords: ['cvs health']},
    {label: 'CVX', keywords: ['chevron']},
    {label: 'DASH', keywords: ['doordash']},
    {label: 'DE', keywords: ['deere', 'john deere']},
    {label: 'DELL', keywords: ['dell technologies']},
    {label: 'DIS', keywords: ['disney', 'walt disney']},
    {label: 'DUK', keywords: ['duke energy']},
    {label: 'ECL', keywords: ['ecolab']},
    {label: 'EQIX', keywords: ['equinix']},
    {label: 'ETN', keywords: ['eaton']},
    {label: 'FDX', keywords: ['fedex']},
    {label: 'GE', keywords: ['ge aerospace', 'general electric']},
    {label: 'GILD', keywords: ['gilead sciences']},
    {label: 'GM', keywords: ['general motors']},
    {label: 'GOOGL', keywords: ['google', 'alphabet']},
    {label: 'GS', keywords: ['goldman sachs']},
    {label: 'HD', keywords: ['home depot']},
    {label: 'HON', keywords: ['honeywell']},
    {label: 'IBM', keywords: ['ibm']},
    {label: 'INTC', keywords: ['intel']},
    {label: 'INTU', keywords: ['intuit']},
    {label: 'ISRG', keywords: ['intuitive surgical']},
    {label: 'JPM', keywords: ['jpmorgan', 'jp morgan']},
    {label: 'KKR', keywords: ['kkr']},
    {label: 'KLAC', keywords: ['kla']},
    {label: 'KO', keywords: ['coca-cola', 'coca cola']},
    {label: 'LIN', keywords: ['linde']},
    {label: 'LLY', keywords: ['eli lilly', 'lilly']},
    {label: 'LOW', keywords: ['lowes', 'lowe\'s']},
    {label: 'LRCX', keywords: ['lam research']},
    {label: 'MA', keywords: ['mastercard']},
    {label: 'MAR', keywords: ['marriott']},
    {label: 'MCD', keywords: ['mcdonalds', 'mcdonald\'s']},
    {label: 'MCK', keywords: ['mckesson']},
    {label: 'MCO', keywords: ['moodys']},
    {label: 'MDLZ', keywords: ['mondelez']},
    {label: 'MDT', keywords: ['medtronic']},
    {label: 'MELI', keywords: ['mercadolibre']},
    {label: 'META', keywords: ['meta platforms', 'facebook']},
    {label: 'MMM', keywords: ['3m']},
    {label: 'MO', keywords: ['altria']},
    {label: 'MRK', keywords: ['merck']},
    {label: 'MS', keywords: ['morgan stanley']},
    {label: 'MSFT', keywords: ['microsoft']},
    {label: 'MSTR', keywords: ['microstrategy', 'strategy']},
    {label: 'MU', keywords: ['micron']},
    {label: 'NDX', symbol: '^ndq', priceDecimals: 0, keywords: ['nasdaq 100', 'nasdaq', 'index']},
    {label: 'NFLX', keywords: ['netflix']},
    {label: 'NKE', keywords: ['nike']},
    {label: 'NOW', keywords: ['servicenow', 'service now']},
    {label: 'NVDA', keywords: ['nvidia']},
    {label: 'ORCL', keywords: ['oracle']},
    {label: 'PANW', keywords: ['palo alto networks', 'palo alto']},
    {label: 'PEP', keywords: ['pepsico', 'pepsi']},
    {label: 'PFE', keywords: ['pfizer']},
    {label: 'PG', keywords: ['procter & gamble', 'procter and gamble']},
    {label: 'PGR', keywords: ['progressive']},
    {label: 'PLD', keywords: ['prologis']},
    {label: 'PLTR', keywords: ['palantir']},
    {label: 'PM', keywords: ['philip morris']},
    {label: 'PYPL', keywords: ['paypal']},
    {label: 'QCOM', keywords: ['qualcomm']},
    {label: 'RTX', keywords: ['rtx', 'raytheon']},
    {label: 'SBUX', keywords: ['starbucks']},
    {label: 'SCHW', keywords: ['charles schwab', 'schwab']},
    {label: 'SNOW', keywords: ['snowflake']},
    {label: 'SO', keywords: ['southern company']},
    {label: 'SPX', symbol: '^spx', priceDecimals: 0, keywords: ['s&p 500', 'sp500', 'index']},
    {label: 'SYK', keywords: ['stryker']},
    {label: 'T', keywords: ['at&t', 'att']},
    {label: 'TGT', keywords: ['target']},
    {label: 'TMO', keywords: ['thermo fisher', 'thermo fisher scientific']},
    {label: 'TMUS', keywords: ['t-mobile', 'tmobile']},
    {label: 'TSLA', keywords: ['tesla']},
    {label: 'TT', keywords: ['trane technologies', 'trane']},
    {label: 'TXN', keywords: ['texas instruments']},
    {label: 'UBER', keywords: ['uber']},
    {label: 'UNH', keywords: ['unitedhealth', 'unitedhealth group']},
    {label: 'UNP', keywords: ['union pacific']},
    {label: 'UPS', keywords: ['united parcel service']},
    {label: 'USB', keywords: ['u.s. bancorp', 'us bancorp']},
    {label: 'V', keywords: ['visa']},
    {label: 'VZ', keywords: ['verizon']},
    {label: 'WELL', keywords: ['welltower']},
    {label: 'WFC', keywords: ['wells fargo']},
    {label: 'WMT', keywords: ['walmart']},
    {label: 'XOM', keywords: ['exxon', 'exxon mobil']},
    {label: 'ZTS', keywords: ['zoetis']},
].map(entry => ({
    assetCategory: ASSET_CATEGORIES.EQUITY,
    label: entry.label,
    symbol: entry.symbol ?? `${entry.label.toLowerCase()}.us`,
    priceDecimals: entry.priceDecimals ?? 2,
    keywords: [...entry.keywords],
}));
